module.exports = {
	practice: [
		"LinearSearchList",
		"BinarySearchList",
		"BubbleSort",
		"InsertionSort",
		"SelectionSort",
		"TwoCrystalBalls",
	],
	dsa: [
		"DFSOnBST",
		"LRU",
		"LinearSearchList",
		"BinarySearchList",
		"TwoCrystalBalls",
		"BubbleSort",
		"InsertionSort",
		"SelectionSort",
		"SinglyLinkedList",
		"DoublyLinkedList",
		"Queue",
		"Stack",
		"ArrayList",
		"MazeSolver",
		"QuickSort",
		"BTPreOrder",
		"BTInOrder",
		"BTPostOrder",
		"BTBFS",
		"CompareBinaryTrees",
		"DFSOnBST",
		"DFSGraphList",
		"Trie",
		"BFSGraphMatrix",
		"Map",
		"MinHeap",
	],
}

